site_name: SchedX
site_description: "A Notebook-Driven Scheduling System with Analytical Modules"
theme:
  name: material

plugins:
  - search
  - mkdocs-jupyter
  - mkdocstrings:
      handlers:
        python:
          paths: [ . ]

nav:
  - Home: index.md
  - Notebook:
      - Schedule-X Notebook: schedule-x.ipynb
  - Modules:
      - Boogr: modules/boogr.md
      - Guro: modules/guro.md
      - Minion: modules/minion.md
      - Mathy:
          - Overview: modules/mathy/index.md
          - Classifiers: modules/mathy/classifiers.md
          - Regressors: modules/mathy/regressors.md
          - Clusters: modules/mathy/clusters.md
          - Data: modules/mathy/data.md
          - Preprocessors: modules/mathy/preprocessors.md
  - License: license.md
